"""initial_schema

Revision ID: 055c17778db0
Revises: 
Create Date: 2026-02-21 15:22:02.530925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055c17778db0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('grandparent', 'grandchild', 'trustee', name='user_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grandparent_id', sa.UUID(), nullable=False),
    sa.Column('grandchild_id', sa.UUID(), nullable=False),
    sa.Column('grandchild_name', sa.String(), nullable=True),
    sa.Column('corpus', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'INR', name='currencies'), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Active', 'Under Review', 'Approved', 'Rejected', 'Redirected', 'Completed', name='gift_statuses'), nullable=True),
    sa.Column('risk_profile', sa.Enum('Conservative', 'Balanced', 'Growth', name='risk_profiles'), nullable=True),
    sa.Column('rule_type', sa.Enum('Time', 'Milestone', 'Behavior', name='rule_types'), nullable=True),
    sa.Column('fallback_ngo_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['grandchild_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grandparent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('grandparent', 'grandchild', 'trustee', name='user_roles_context'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gift_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('text', 'photo', 'audio', 'video', name='media_types'), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gift_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Submitted', 'Approved', 'Rejected', name='milestone_statuses'), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('override_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gift_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Overridden', 'Expired', name='override_statuses'), nullable=True),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('override_windows')
    op.drop_table('milestones')
    op.drop_table('media_messages')
    op.drop_table('notifications')
    op.drop_table('gifts')
    op.drop_table('users')
    # ### end Alembic commands ###
